version: '3'
services:
  kahunabooking:
    image: 'softwaremill/kahunabooking:latest'
    ports:
      - '8080:8080'
    depends_on:
      - kahunabooking-db
    environment:
      SQL_USERNAME: 'postgres'
      SQL_PASSWORD: 'b00t200k4'
      SQL_DBNAME: 'kahunabooking'
      SQL_HOST: 'kahunabooking-db'
      SQL_PORT: '5432'
      API_HOST: '0.0.0.0'
  kahunabooking-db:
    image: 'postgres'
    ports:
      - '25432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'b00t200k4'
      POSTGRES_DB: 'kahunabooking'
