apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "kahunabooking.fullname" . }}-secret
data:
  SQL_PASSWORD: {{ tpl .Values.kahunabooking.sql.password . | b64enc | quote }}
  SMTP_PASSWORD: {{ tpl .Values.kahunabooking.smtp.password . | b64enc | quote }}
